## Máster en Big Data y Data Science

### Metodologías de gestión y diseño de proyectos de big data

#### Sesión Práctica 01 - Ejemplo dvc

---

En esta libreta se realizan una serie de pasos básicos para verificar la operatoria a seguir con respecto al versionado de datos utilizando la librería dvc.

In [1]:
import pandas as pd

Se realiza en primera instancia la lectura del conjunto de datos.

In [2]:
df_ejemplo = pd.DataFrame({
    'apellido': ['Perez', 'Gomez', 'Fernandez'],
    'nombre': ['Juan', 'Maria', 'Carlos'],
    'edad': [28, 34, 45]
})

df_ejemplo.to_csv("../data/raw/ejemplo.csv", sep=";", index=False)
df_ejemplo.head()

    apellido  nombre  edad
0      Perez    Juan    28
1      Gomez   Maria    34
2  Fernandez  Carlos    45

En este punto, el dataset debe haber sido versionado y se habrán confirmado los cambios en el repositiorio git.

A continuación se realiza una modificación para verificar el funcionamiento de dvc.

In [3]:
# Se eliminan dos columnas solo a modo de ejemplo

df_ejemplo.drop(columns=['edad'], inplace=True)
df_ejemplo.head(1)

  apellido nombre
0    Perez   Juan

In [4]:
# Se escriben los cambios al archivo para poder aplicarlos y revertirlos posteriormente.

df_ejemplo.to_csv("../data/raw/ejemplo.csv", sep=";", index=False)

Estos cambios deberán ser confirmados en dvc y en el repositorio git.